const nav=document.querySelector('.nav');const menu=document.querySelector('.menu');menu?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const data={
 lead:{title:'Lead Management & Follow-up',type:'CRM configuration',img:'assets/leads.jpg',problem:'Make lead follow-up easier by giving users a clear list of leads, ownership, status, source and activity context.',built:['Lead list view and filtering','Lead fields/layout visibility','Owner and activity visibility','A practical “My Leads” workspace'],tools:'Leads, list views, fields, activities',interview:'I would explain the requirement first, then show how the list view reduces noise and helps a sales user focus on actionable leads.',question:'How would you design a Lead list view for a sales team? Start with user needs, choose useful columns and filters, and test that the view matches the team workflow.'},
 opp:{title:'Opportunity Pipeline',type:'Sales CRM',img:'assets/opportunities.jpg',problem:'Create a cleaner way to inspect opportunities by account, stage, close date and owner.',built:['Opportunity list view','Stage-based visibility','Close-date inspection','Account and owner context'],tools:'Opportunities, stages, list views, reporting',interview:'The important admin skill is translating “I need better pipeline visibility” into specific fields, filters and reporting requirements.',question:'When would you use a list view versus a report? Use a list view for focused record work; use a report when you need grouping, summaries or broader analysis.'},
 dashboard:{title:'Global Sales Dashboard',type:'Analytics',img:'assets/dashboard.jpg',problem:'Give a management-style snapshot of pipeline and sales performance in one place.',built:['Sales Pipeline chart','Opportunities Won table','Total Open Opportunities KPI','Company Win Rate gauge'],tools:'Reports, dashboard components, groupings, summaries',interview:'The dashboard is built from reports. I would explain the business question behind each component rather than only describing the chart.',question:'What makes a good dashboard? Clear business questions, trusted source reports, useful KPIs, readable components and appropriate filters.'},
 bigdeals:{title:'Big Deals Dashboard',type:'Analytics',img:'assets/bigdeals.jpg',problem:'Surface opportunity concentration by stage so a sales user can quickly inspect the pipeline.',built:['Opportunity stage distribution','Record-count visualization','Dashboard component','Report drill-through'],tools:'Opportunity report + dashboard',interview:'I would walk through the report behind the chart, the grouping by stage and how the dashboard helps a user identify where opportunities sit.',question:'How do you create a dashboard component? Build/validate the source report, choose the component type, configure grouping/metrics, then test the result.'},
 winrate:{title:'Sales Rep Win Rate',type:'Reporting',img:'assets/winrate.jpg',problem:'Measure opportunity outcomes with grouped summaries that make win-rate performance visible.',built:['Grouped by Opportunity Owner','Close-date grouping','Amount summary','Win-rate metric'],tools:'Summary/matrix-style reporting and dashboard visualization',interview:'I would explain the underlying report logic, not just the 100% figure visible in the demo screenshot.',question:'How would you calculate win rate? Define the business formula first, ensure Closed Won/Closed Lost data is reliable, then build a report or summary using the correct denominator.'},
 agent:{title:'Agentforce Support FAQ Agent',type:'AI + Service',img:'assets/agentforce2.jpg',problem:'Design a support agent that routes intents, verifies customers before sensitive actions, answers FAQs and escalates to a human when required.',built:['Agent Router','Service Customer Verification','General FAQ','Case Management','Account Management','Reservation Management','Delivery Issues','Order Inquiries','Escalation','Off Topic / Ambiguous Question paths'],tools:'Agentforce Builder, subagents, instructions, live test/trace',interview:'I would describe the agent as a controlled routing system: understand intent, move to the right subagent, verify identity where needed, ground responses in the right data and provide a human escalation path.',question:'Why verify identity before order status? Because order information can be sensitive; the agent should establish the required customer context before exposing protected information.'}
};
const modal=document.getElementById('modal'),content=document.getElementById('modalContent');function openCase(key){const d=data[key];content.innerHTML=`<div class="eyebrow">${d.type}</div><h2>${d.title}</h2><h4>Business problem</h4><p>${d.problem}</p><h4>What I built</h4><ul>${d.built.map(x=>`<li>${x}</li>`).join('')}</ul><h4>Salesforce tools / concepts</h4><p>${d.tools}</p><h4>How I would explain it in an interview</h4><p>${d.interview}</p><h4>Likely interviewer question</h4><p><b>${d.question}</b></p><img src="${d.img}" alt="${d.title} evidence">`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
document.querySelectorAll('.case').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.case)));document.querySelector('.close').addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
